name: 'build test'

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: JDK ${{ matrix.java }}
    strategy:
      matrix:
        java: [ "17" ]

    steps:
      - name: Checkout...
        uses: actions/checkout@v2

      - name: Set up JDK...
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Retrieve mvn repo cache...
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-build-v2

      - name: agrest4-jaxrs-cayenne
        run: cd agrest4-jaxrs-cayenne/ && mvn clean verify

      - name: agrest5-jaxrs3-cayenne
        run: cd agrest5-jaxrs3-cayenne/ && mvn clean verify
